name: monorepo-split

on:
  push:
    tags: '*'

jobs:
  split-monorepo:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - actions
          - forms
          - infolists
          - notifications
          - panels
          - spatie-laravel-media-library-plugin
          - spatie-laravel-tags-plugin
          - support
          - tables
          - widgets
    steps:
      - uses: actions/checkout@v3
      - id: previous-tag
        uses: 'WyriHaximus/github-action-get-previous-tag@master'
      - name: Monorepo Split of ${{ matrix.package }}
        uses: danharrin/monorepo-split-github-action@v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          package_directory: 'packages/${{ matrix.package }}'
          repository_organization: 'aiv-damian'
          repository_name: '${{ matrix.package }}'
          branch: 3.x
          tag: ${{ steps.previous-tag.outputs.tag }}
          user_name: 'Damian de Jong'
          user_email: 'damian@aiv-automatisering.nl'
